# Generated by Django 2.1.8 on 2019-05-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bofy',
            new_name='body',
        ),
    ]
