# Generated by Django 2.1.8 on 2019-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190511_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(),
        ),
    ]
