# Generated by Django 2.1.8 on 2019-05-11 17:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190511_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/featured-images'), upload_to=''),
        ),
    ]
