# Generated by Django 2.1.8 on 2019-05-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
