# Generated by Django 2.1.8 on 2019-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
    ]
