# Generated by Django 2.1.8 on 2019-06-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
